name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Test secret
    runs-on: ubuntu-latest
    steps:

    - name: Context in env
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: ''

    - name: Checkout
      uses: actions/checkout@v1

    - name: Test secret
      shell: bash
      run: |
        set -x
        echo "${SECRET}"
